"use client"
import Link from "next/link";
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const onClick = (url: string) => {
    router.push(url);
  };
  return (
    <html lang="en">
      <body>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/dashboard">Dashboard</Link>
          </li>
          <li>
            <Link href="/calculator">Calculator</Link>
          </li>
          <li
            style={{
              backgroundColor: "#000",
              color: "#fff",
              padding: "10px",
              cursor: "pointer",
            }}
            onClick={() => onClick("/settings")}
          >
            Settings
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
