"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const onClick = (url: string) => {
    router.push(url);
  };

  const menuItem = (url: string, title: string) => {
    return (
      <li className="bg-black text-white py-2 px-3 rounded-lg">
        <Link href={url}>{title}</Link>
      </li>
    );
  };
  return (
    <html lang="en">
      <body className="container mx-auto py-[10px]">
        <ul className="inline-flex space-x-3 w-full">
          {menuItem("/", "Home")}
          {menuItem("/dashboard", "Dashboard")}
          {menuItem("/settings", "Settings")}
          {menuItem("/search", "Search")}
          {menuItem("/calculator", "Calculator")}
        </ul>
        {children}
      </body>
    </html>
  );
}
